### ISSUE TITLE
Categories API

### ISSUE THREAD

**Issue by jeromewu** [codeday-labs/bookworms#18]
![codeday-project-wireframe-list](https://user-images.githubusercontent.com/5723124/124890681-dd2de780-e00a-11eb-9972-0973251c3eef.png)

On the right hand side of the review list view, there is a category filter to filter for certain categories, as our categories is defined by the user at the moment, **we need an API to get a list of user defined categories** to allow user to filter based on available categories.

**Comment by veritem** [comment]
This has been fixed #17 use this endpoint `/api/categories`
