### ISSUE TITLE
Likes button and show number of likes

### ISSUE THREAD

**Issue by dknv** [codeday-labs/bookworms#24]
Likes button is not independent from review to review yet :(

**Comment by jeromewu** [comment]
Yeah, I think you need to create a LikeButton to keep its own state.

**Comment by dknv** [comment]
That would mean I have to create a class called LikeButton and import that into the homepage?

**Comment by jeromewu** [comment]
Yes, or simply a function can do:

```javascript
function LikeButton() {
  const [isLiked, setIsLiked] = useState(...);
  return (...)
}
```
