### ISSUE TITLE
Defer after error handling

### ISSUE THREAD

**Issue by jeromewu** [codeday-labs/bookworms#33]
There was a mistake for the place of calling defer func.

Take this one as an example:

```go
	DB, err := db.DB()

	defer func() {
		if err := DB.Client().Disconnect(db.Ctx); err != nil {
			panic(err)
		}
	}()

	if err != nil {
		return nil, err
	}
```

As `DB` becomes nil when there is an error, this will cause a panic (nil pointer dereference) in defer func and it is not an expected behavior, so the defer should go after error handling:

```go
	DB, err := db.DB()

	if err != nil {
		return nil, err
	}

        defer func() {
		if err := DB.Client().Disconnect(db.Ctx); err != nil {
			panic(err)
		}
	}()
```

I must be confused with other cases, and hope this correction can help you in the future.

**Comment by veritem** [comment]
Thanks for pointing this out.
